name: Unity Windows Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
      UNITY_USERNAME: ${{ secrets.UNITY_USERNAME }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Unity
      uses: game-ci/setup-unity@v1
      with:
         unityVersion: 2020.3.18f1  # Specify the Unity version
         unityLicense: ${{ secrets.UNITY_LICENSE }}

    - name: Unity - Test Runner
      uses: game-ci/unity-test-runner@v2
      with:
         projectPath: Unity-UnitTestingPong/Assets/Tests/EditorTests  # Adjust the path to your tests
         githubToken: ${{ secrets.GITHUB_TOKEN }}
         
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: |
          windows/UnitTestingPong.exe
          tests.xml
