name: Unity Windows Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
      UNITY_USERNAME: ${{ secrets.UNITY_USERNAME }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Unity
      run: |
        $env:UNITY_BIN = "${env:UNITY_HOME}\Editor\Unity.exe"

    - name: Request manual activation file
      id: getManualLicenseFile
      uses: game-ci/unity-request-activation-file@v2
      # Upload artifact (Unity_v20XX.X.XXXX.alf)
    - name: Expose as artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.getManualLicenseFile.outputs.filePath }}
        path: ${{ steps.getManualLicenseFile.outputs.filePath }}
        
    - name: Run Unit Tests
      run: $env:UNITY_BIN -executeMethod Runner.RunUnitTests -logFile -nographics -projectPath . -testsOutput tests.xml
      continue-on-error: true  # Tests may fail but we want to continue

    - name: Build
      run: $env:UNITY_BIN -batchmode -quit -logFile -projectPath . -executeMethod BuildScript.BuildWindows -nographics

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: |
          windows/UnitTestingPong.exe
          tests.xml
