name: Unity Windows Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
      UNITY_USERNAME: ${{ secrets.UNITY_USERNAME }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Unity
      run: |
        $env:UNITY_BIN = "${env:UNITY_HOME}\Editor\Unity.exe"

    - name: Unity - Request Activation File
      uses: game-ci/unity-request-activation-file@v2.0.0
            
    - name : Unity - Test Runner
      uses: game-ci/unity-test-runner@v2
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}  
      with:
        unityVersion: 2020.3.18f1
        projectPath: C:/Users/yhyya/scc/Unity-UnitTestingPong/Assets/Tests/EditorTests
        githubToken: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: |
          windows/UnitTestingPong.exe
          tests.xml
